Decimus/Subscriptions/VideoHandler.swift
Fixup the labels post-MoQ rewrite
=> Restore label functionality

Decimus/CallController.swift, Decimus/Publications/H264Publication.swift, Decimus/Publications/OpusPublication.swift, Decimus/Publications/Publication.swift, Decimus/Subscriptions/OpusSubscription.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Subscriptions/VideoSubscription.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, Decimus/Views/InCallView.swift
Ensure long running tasks don't hold up destruction with badly scoped weak->strong references.
=> Strong ref tasks

Decimus/CallController.swift, Decimus/Lib/libquicr/QClient.h, Decimus/Lib/libquicr/QClientCallbacks.h, Decimus/Lib/libquicr/QClientObjC.mm, Decimus/Lib/libquicr/QCommon.h, Decimus/Lib/libquicr/QPublishTrackHandler.h, Decimus/Lib/libquicr/QPublishTrackHandlerCallbacks.h, Decimus/Lib/libquicr/QPublishTrackHandlerObjC.mm, Decimus/Lib/libquicr/QSubscribeTrackHandler.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerCallbacks.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.mm, Decimus/Measurements/CallController+Measurement.swift, Decimus/Measurements/TrackMeasurement.swift, Decimus/Publications/H264Publication.swift, Decimus/Publications/OpusPublication.swift, Decimus/Publications/Publication.swift, Decimus/Publications/PublicationFactory.swift, Decimus/Subscriptions/OpusSubscription.swift, Decimus/Subscriptions/VideoSubscription.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, Decimus/Views/InCallView.swift, QuicR.xcodeproj/project.pbxproj, Tests/TestCallController.swift, Tests/TestOpusPublication.swift, Tests/TestOpusSubscription.swift, Tests/TestPublication.swift, Tests/TestVideoPublication.swift, Tests/TestVideoSubscription.swift, Tests/TestVideoSubscriptionSet.swift
Reports metrics with the same identifiers as existing dashboards.
TODO:
=> Report libquicr metrics

Decimus/Subscriptions/VideoHandler.swift
Hotfix for the issue in #492. Will investigate further and add tests.
=> Remove waitTime fatalErrors

Decimus/CaptureManager.swift, Decimus/Codec/VTEncoder.swift, Decimus/DecimusApp.swift, Decimus/DecimusAudioEngine.swift, Decimus/Publications/OpusPublication.swift, Decimus/Publications/PublicationFactory.swift, Decimus/VideoDevices.swift, Decimus/Views/CallSetupView.swift, Decimus/Views/Components/ActionButton.swift, Decimus/Views/Components/ActionPicker.swift, Decimus/Views/Components/CallControls.swift, Decimus/Views/Components/LabeledToggle.swift, Decimus/Views/Components/PreviewView.swift, Decimus/Views/Components/ViewExtensions.swift, Decimus/Views/ConfigCallView.swift, Decimus/Views/InCallView.swift, Decimus/Views/NumberView.swift, Decimus/Views/Settings/InfluxSettingsView.swift, Decimus/Views/Settings/ManifestSettingsView.swift, Decimus/Views/Settings/RelaySettingsView.swift, Decimus/Views/Settings/SettingsView.swift, Decimus/Views/Settings/SubscriptionSettingsView.swift, Decimus/Views/Settings/TransportConfigSettings.swift, Decimus/Views/Settings/VideoJitterBufferSettingsView.swift, Decimus/Views/VideoView.swift, QuicR.xcodeproj/project.pbxproj, dependencies/build-qmedia-framework.py, dependencies/make_universal.sh
Provided as a (temporary?) workaround for #495 by leveraging a native MacOS build for working pure-software camera extensions. 
-  [ ] UI, particularly the settings UI, is messed up.
=> Build for native macOS

Decimus/Lib/libquicr/FullTrackName.swift, Decimus/Lib/libquicr/QClientObjC.mm, Decimus/Lib/libquicr/QFullTrackName.h, Decimus/Lib/libquicr/QFullTrackName.mm, Decimus/Lib/libquicr/QPublishTrackHandlerObjC.mm, Decimus/Lib/libquicr/QSubscribeTrackHandler.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.mm, Decimus/Subscriptions/OpusSubscription.swift, Decimus/Subscriptions/VideoSubscription.swift, Tests/TestCallController.swift
Adhere to upstream API changes
=> Namespace tuple

Decimus/Lib/libquicr/LowOverheadContainer.swift, Decimus/Publications/OpusPublication.swift
Send audio energy level in audio object LOC. 
Closes #513
=> Add audio energy level into LOC

Decimus/Views/Components/VideoGrid.swift, Decimus/Views/InCallView.swift, Decimus/Views/Settings/PlaytimeSettingsView.swift, Decimus/Views/Settings/SettingsView.swift, QuicR.xcodeproj/project.pbxproj
- Initial setting for restricting grid count
=> Add feature toggle for playtime

Decimus/CallController.swift
=> Hotfix connect continuation

.swiftlint.yml, ci_scripts/analyze.sh
Setup script for running `swiftlint analyze`. Later to be added to CI build or commit hook.
=> Setup for swiftlint analyze

Decimus/DecimusAudioEngine.swift, Decimus/Publications/OpusPublication.swift, Decimus/Subscriptions/OpusHandler.swift, Decimus/Subscriptions/SubscriptionFactory.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, Decimus/TokenStorage.swift, Decimus/Views/Components/SubscriptionPopover.swift, Decimus/Views/Settings/InfluxSettingsView.swift, QuicR.xcodeproj/project.pbxproj, Tests/TestActiveSpeaker.swift, Tests/TestCallController.swift, Tests/TestVideoJitterBuffer.swift
=> Swiftlint reenable

Decimus/Subscriptions/OpusHandler.swift
=> Don't PLC on backwards discontinuity

Config.xcconfig, Decimus/JitterBuffer.swift, Decimus/SlidingWindow.swift, Decimus/Subscriptions/SubscriptionFactory.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, Decimus/Views/Settings/SubscriptionSettingsView.swift, QuicR.xcodeproj/project.pbxproj, Tests/TestSlidingWindow.swift
Calculate the timestamp difference using a sliding window over a configurable period, rather than the first received object.
=> Sliding timestamp window

Config.xcconfig, Decimus/Lib/libquicr/QMediaTypes.swift, Decimus/Lib/libquicr/QPublishTrackHandlerCallbacks.h, Decimus/Lib/libquicr/QPublishTrackHandlerObjC.h, Decimus/Lib/libquicr/QPublishTrackHandlerObjC.mm, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.mm, Decimus/Publications/H264Publication.swift, Tests/TestVideoPublication.swift
Ref https://github.com/Quicr/libquicr/pull/443/
=> Add bindings for new group

Config.xcconfig, Decimus/SlidingWindow.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift
This shouldn't have been in the callback thread. Moved to task, added thread safety.
=> Move sliding window calc off cb thread

Config.xcconfig, Decimus/Views/CallSetupView.swift, Decimus/Views/ConfigCallView.swift
- Fixes issue where you can see no picker despite a valid email address. 
- Remove view initialisers / callback logic in favour of SwiftUI binding. 
- Simplify redraw / recompute logic on change
- Ensure buttons / spinners are set to active or inactive where appropriate
=> SwiftUI-ify & refactor call setup logic

Config.xcconfig, Decimus/SlidingWindow.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, QuicR.xcodeproj/project.pbxproj, Tests/TestSlidingWindow.swift, Tests/TestVideoSubscriptionSet.swift
Been on the cards for a while but this moves to iOS 18 & MacOS 15 for `Synchronization`.
=> Ensure future timestamps are handled correctly

.swiftlint.yml, Config.xcconfig, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.mm, Decimus/Models/VideoParticipant.swift, Decimus/Subscriptions/SubscriptionFactory.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Subscriptions/VideoSubscription.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, Decimus/Views/Settings/SubscriptionSettingsView.swift, Tests/TestVideoSubscription.swift
New join flow. 
FETCH if you're close to the start.
NEWGROUP if you're in the middle.
Wait if you're near the end.
=> New joining flow

Config.xcconfig, Decimus/Subscriptions/OpusHandler.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Subscriptions/VideoSubscriptionSet.swift, Decimus/TimeAligned.swift, QuicR.xcodeproj/project.pbxproj, QuicR.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, QuicR.xcodeproj/xcshareddata/IDETemplateMacros.plist, Tests/TestTimeAlign.swift
Handle video and audio time calculations the same
=> Audio time

Config.xcconfig, Decimus/ActiveSpeakerStats.swift, Decimus/Codec/CodecFactory.swift, Decimus/Measurements/ActiveSpeakerStats+Measurement.swift, Decimus/Subscriptions/ActiveSpeakerNotifier.swift, Decimus/Subscriptions/OpusSubscription.swift, Decimus/Subscriptions/SubscriptionFactory.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Subscriptions/VideoSubscription.swift, Decimus/Views/Components/VideoGrid.swift, Decimus/Views/InCallView.swift, QuicR.xcodeproj/project.pbxproj, Tests/TestActiveSpeakerStats.swift, Tests/TestVideoSubscription.swift
- Only compute on real reports, not internal switches
- Compute on non active speaker subscriptions when in manual mode
- Readd test case
- Fix waiting for new group join flow
=> AS stats fixup

Config.xcconfig, Decimus/CallController.swift, Decimus/CallState.swift, Decimus/CircularBuffer.swift, Decimus/Codec/LibOpusDecoder.swift, Decimus/DecimusAudioEngine.swift, Decimus/ErrorWriter.swift, Decimus/Lib/libquicr/FullTrackName.swift, Decimus/Lib/libquicr/LowOverheadContainer.swift, Decimus/Models/ManifestTypes.swift, Decimus/Publications/AudioPublication.swift, Decimus/Publications/OpusPublication.swift, Decimus/Publications/PublicationFactory.swift, Decimus/Subscriptions/ActiveSpeakerSubscriptionSet.swift, Decimus/Subscriptions/AudioHandler.swift, Decimus/Subscriptions/OpusSubscription.swift, Decimus/Subscriptions/SubscriptionFactory.swift, Decimus/Subscriptions/VideoHandler.swift, Decimus/Views/Components/VideoGrid.swift, Decimus/Views/ConfigCallView.swift, Decimus/Views/InCallView.swift, QuicR.xcodeproj/project.pbxproj
Remove InCallView view model in favour of a dedicated `CallState` object. This provides better flexibility for alternative call views.
=> Call State rearch

Config.xcconfig, Decimus/Codec/LibOpusDecoder.swift, Decimus/JitterBuffer.swift, Decimus/Subscriptions/ActiveSpeakerSubscriptionSet.swift, Decimus/Subscriptions/AudioHandler.swift, Decimus/Subscriptions/OpusSubscription.swift, Decimus/Subscriptions/SubscriptionFactory.swift, Decimus/Views/Settings/SubscriptionSettingsView.swift
A large change in group ID should not be treated as a large discontinuity and cause PLC. Instead, reset state and continue.
=> Reset on large discontinuities

Config.xcconfig, Decimus/Measurements/OpusSubscription+Measurement.swift, Decimus/Subscriptions/AudioHandler.swift, Decimus/Subscriptions/VideoHandler.swift
Do silence detection in chunks (currently set to 5ms).
=> Do silence checking in chunks

Decimus/Lib/Decimus-Bridging-Header.h, Decimus/Lib/libquicr/QLocation.h, Decimus/Lib/libquicr/QLocation.mm, Decimus/Lib/libquicr/QPublishTrackHandler.h, Decimus/Lib/libquicr/QPublishTrackHandlerObjC.h, Decimus/Lib/libquicr/QPublishTrackHandlerObjC.mm, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.mm, Decimus/Publications/H264Publication.swift, Decimus/Publications/OpusPublication.swift, QuicR.xcodeproj/project.pbxproj, Tests/TestCallController.swift
Update to support latest libquicr release supporting Draft11.
=> Update to draft-11

Decimus/CallController.swift, Decimus/CallState.swift, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.h, Decimus/Lib/libquicr/QSubscribeTrackHandlerObjC.mm, Decimus/Subscriptions/Subscription.swift, dependencies/build-qmedia-framework.py
=> Add delivery timeout to be used by group time queue. 

Config.xcconfig, Decimus/Views/Settings/InfluxSettingsView.swift, Decimus/Views/Settings/ManifestSettingsView.swift, Decimus/Views/Settings/SettingsView.swift, Decimus/Views/Settings/SubscriptionSettingsView.swift
Closes #518. Fixes settings UI on non-catalyst MacOS. Fix typos in settings.
=> Fix inconsistent settings UI views
